server:
  port: 0
spring:
  application:
    name: catalog-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

queue:
  serie:
    name: serieQueue
  movie:
    name: movieQueue


  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: Catalog
      port: 27017

management:
  tracing:
    sampling:
      probability: 1.0