server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: movie-service
  cloud:
    config:
      enabled: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3366/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


management:
  tracing:
    sampling:
      probability: 1.0

queue:
  movie:
    name: movieQueue


