eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        lease-expiration-duration-in-seconds: 10
        lease-renewal-interval-in-seconds: 5
        prefer-ip-address: true
management:
    tracing:
        sampling:
            probability: 1.0
queue:
    serie:
        name: serieQueue
server:
    port: ${PORT:${SERVER_PORT:0}}
spring:
    application:
        name: serie-service
    data:
        mongodb:
            database: test
            port: 27017
    mongodb:
        embedded:
            version: 4.0.2
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest
